SCRIPT_VERSION="3.2.2"
SCRIPT_AUTHOR="ike"
SCRIPT_NAME="NoBrand-OneClick"
SCRIPT_REPO="ike-sh/NoBrand-OneClick"
NOBRAND_SCHEMA_VERSION=3
UPSTREAM_REPO="enfein/mieru"
LAST_KNOWN_GOOD_MIERU_VERSION="3.36.0"
# Retained as a source-compatible public constant for parity consumers.
# shellcheck disable=SC2034
TESTED_MIERU_VERSION="$LAST_KNOWN_GOOD_MIERU_VERSION"
NOBRAND_MIERU_RELEASES_API="https://api.github.com/repos/${UPSTREAM_REPO}/releases"
GITHUB_DL="https://github.com/${UPSTREAM_REPO}/releases/download"
LAST_KNOWN_GOOD_MIERU_AMD64_DEB_SHA256="44622bea7fac732984ac6cf1189e555fd9add1969001e9b2d7cdea9416b5919a"
LAST_KNOWN_GOOD_MIERU_ARM64_DEB_SHA256="a43dbc4d75dcb18978ea79b924ce859e2485af8b776dfc981b29a7b60644157c"
LAST_KNOWN_GOOD_MIERU_AMD64_RPM_SHA256="9504eefed0009b79246c58f5e27a7a24ac2edb6c48710099eb53afde847e84a2"
LAST_KNOWN_GOOD_MIERU_ARM64_RPM_SHA256="5cba9b07771998263447607212cf91bc2c7feb7ec51d96f026c788ff055e378a"
LAST_KNOWN_GOOD_MIERU_AMD64_TAR_SHA256="d61f35c463f101580a108dd6b969e1a3dca1b84836332b2533302a62e70f04bb"
LAST_KNOWN_GOOD_MIERU_ARM64_TAR_SHA256="12b811bc00364bed2188d6e13e38cb7e727d149e488a3805f8c97f3f7f6e3bd6"

# NoBrand 3 has one authoritative product-state root. Lifecycle recovery
# metadata and its process lock deliberately live beside, not below, that
# root so an interrupted full uninstall cannot erase the evidence needed by
# the next invocation.
NOBRAND_STATE_DIR="${NOBRAND_STATE_DIR:-/var/lib/nobrand-oneclick}"
NOBRAND_CONFIG_DIR="${NOBRAND_CONFIG_DIR:-/etc/nobrand-oneclick}"
NOBRAND_LIB_DIR="${NOBRAND_LIB_DIR:-/usr/local/lib/nobrand-oneclick}"
NOBRAND_LIFECYCLE_DIR="${NOBRAND_LIFECYCLE_DIR:-/var/lib/nobrand-oneclick-lifecycle}"
NOBRAND_LIFECYCLE_TX_FILE="${NOBRAND_LIFECYCLE_TX_FILE:-${NOBRAND_LIFECYCLE_DIR}/transaction.env}"
NOBRAND_BACKUP_RESTORE_TX_DIR="${NOBRAND_LIFECYCLE_DIR}/backup-restore"
NOBRAND_BACKUP_RESTORE_META_FILE="${NOBRAND_BACKUP_RESTORE_TX_DIR}/transaction.env"
NOBRAND_BACKUP_RESTORE_SNAPSHOT_DIR="${NOBRAND_BACKUP_RESTORE_TX_DIR}/snapshot"
NOBRAND_BACKUP_RESTORE_ROOTS_MANIFEST="${NOBRAND_BACKUP_RESTORE_TX_DIR}/snapshot-roots.manifest"
NOBRAND_LIFECYCLE_LOCK_FILE="${NOBRAND_LIFECYCLE_LOCK_FILE:-/run/nobrand-oneclick/lifecycle.lock}"
NOBRAND_BIN_DIR="${NOBRAND_BIN_DIR:-${NOBRAND_LIB_DIR}/bin}"
NOBRAND_BACKUP_DIR="${NOBRAND_BACKUP_DIR:-${NOBRAND_STATE_DIR}/backups}"
NOBRAND_LOCK_DIR="${NOBRAND_LOCK_DIR:-${NOBRAND_STATE_DIR}/locks}"
NOBRAND_REGISTRY_FILE="${NOBRAND_REGISTRY_FILE:-${NOBRAND_STATE_DIR}/state.json}"
NOBRAND_INGRESS_STATE_FILE="${NOBRAND_INGRESS_STATE_FILE:-${NOBRAND_STATE_DIR}/ingress.json}"
NOBRAND_INGRESS_FIREWALL_STATE_FILE="${NOBRAND_INGRESS_FIREWALL_STATE_FILE:-${NOBRAND_STATE_DIR}/ingress-firewall.json}"
NOBRAND_INGRESS_FIREWALL_RULESET="${NOBRAND_INGRESS_FIREWALL_RULESET:-${NOBRAND_CONFIG_DIR}/ingress-firewall.nft}"
NOBRAND_INGRESS_NFT_FAMILY="${NOBRAND_INGRESS_NFT_FAMILY:-inet}"
NOBRAND_INGRESS_NFT_TABLE="${NOBRAND_INGRESS_NFT_TABLE:-nobrand_ingress}"
NOBRAND_FIREWALL_OWNED_STATE="${NOBRAND_FIREWALL_OWNED_STATE:-${NOBRAND_STATE_DIR}/firewall-owned.bindings}"
NOBRAND_FIREWALL_COMMENT="nobrand-oneclick"
NOBRAND_INSTALL_SCRIPT_PATH="${NOBRAND_INSTALL_SCRIPT_PATH:-/usr/local/bin/install-nobrand}"
NOBRAND_COMMAND_PATH="${NOBRAND_COMMAND_PATH:-/usr/local/bin/nobrand}"
NOBRAND_SHORT_COMMAND_PATH="${NOBRAND_SHORT_COMMAND_PATH:-/usr/local/bin/nb}"
NOBRAND_RELEASE_INSTALLER_URL="https://github.com/${SCRIPT_REPO}/releases/latest/download/install-nobrand.sh"
NOBRAND_LEGACY_MIERU_STATE_DIR="${NOBRAND_LEGACY_MIERU_STATE_DIR:-/var/lib/mita-oneclick}"

# Mieru's official runtime remains named mita, but NoBrand always invokes the
# explicit managed copy below. It is protocol runtime, never a management CLI.
MITA_MANAGER_STATE_DIR="${MITA_MANAGER_STATE_DIR:-${NOBRAND_STATE_DIR}/mieru}"
MITA_BIN="${MITA_BIN:-${NOBRAND_BIN_DIR}/mita}"
MITA_REAL_BIN="${MITA_REAL_BIN:-${MITA_BIN}}"
MITA_PACKAGE_BIN="${MITA_PACKAGE_BIN:-/usr/bin/mita}"
MITA_MARKER="${MITA_MARKER:-${MITA_MANAGER_STATE_DIR}/.installed}"
MITA_STATE="${MITA_STATE:-${MITA_MANAGER_STATE_DIR}/install-state.env}"
MITA_PRESERVE_PACKAGE_MARKER="${MITA_PRESERVE_PACKAGE_MARKER:-${MITA_MANAGER_STATE_DIR}/preserve-preexisting-package}"
MITA_PRESERVE_USER_MARKER="${MITA_PRESERVE_USER_MARKER:-${MITA_MANAGER_STATE_DIR}/preserve-preexisting-user}"
MITA_PRESERVE_GROUP_MARKER="${MITA_PRESERVE_GROUP_MARKER:-${MITA_MANAGER_STATE_DIR}/preserve-preexisting-group}"
MITA_PRESERVE_SHARED_MARKER="${MITA_PRESERVE_SHARED_MARKER:-${MITA_MANAGER_STATE_DIR}/preserve-preexisting-shared-runtime}"
MITA_USERS_STATE="${MITA_USERS_STATE:-${MITA_MANAGER_STATE_DIR}/users.json}"
MITA_USERS_LOCK="${MITA_USERS_LOCK:-${MITA_MANAGER_STATE_DIR}/users.lock}"
MITA_USERS_CRON="${MITA_USERS_CRON:-/etc/cron.d/nobrand-mieru-users}"
MITA_USERS_TIMER="${MITA_USERS_TIMER:-/etc/systemd/system/nobrand-mieru-users-scan.timer}"
MITA_USERS_SERVICE="${MITA_USERS_SERVICE:-/etc/systemd/system/nobrand-mieru-users-scan.service}"
MITA_USERS_LOG="${MITA_USERS_LOG:-/var/log/nobrand-mieru-users.log}"
MITA_USERS_BACKUP_DIR="${MITA_USERS_BACKUP_DIR:-${MITA_MANAGER_STATE_DIR}/backups}"
MITA_ADMIN_LOCK="${MITA_ADMIN_LOCK:-${MITA_MANAGER_STATE_DIR}/admin.lock}"
MITA_CLIENT_EXPORT_DIR="${MITA_CLIENT_EXPORT_DIR:-/root/nobrand-mieru-clients}"
MITA_LOGROTATE_CONF="${MITA_LOGROTATE_CONF:-/etc/logrotate.d/nobrand-mieru}"
MITA_FIREWALL_OWNED_STATE="${MITA_FIREWALL_OWNED_STATE:-${MITA_MANAGER_STATE_DIR}/firewall-owned.bindings}"
MITA_FIREWALL_COMMENT="nobrand-mieru"
MITA_METRICS_FILE="${MITA_METRICS_FILE:-/var/lib/mita/metrics.pb}"
BBR_SYSCTL_CONF="${BBR_SYSCTL_CONF:-/etc/sysctl.d/mieru_tcp_bbr.conf}"
BBR_STATE_FILE="${BBR_STATE_FILE:-${MITA_MANAGER_STATE_DIR}/bbr-owned.state}"
BBR_BACKUP_FILE="${BBR_BACKUP_FILE:-${MITA_MANAGER_STATE_DIR}/bbr-sysctl.backup}"
MITA_DEPLOYMENT_MODEL="isolated-v2"
MITA_INSTANCES_DIR="${MITA_INSTANCES_DIR:-/etc/mita/instances}"
MITA_INSTANCE_RUN_DIR="${MITA_INSTANCE_RUN_DIR:-/run/mita-instances}"
MITA_INSTANCE_METRICS_DIR="${MITA_INSTANCE_METRICS_DIR:-/var/lib/mita/instances}"
MITA_INSTANCE_SYSTEMD_TEMPLATE="${MITA_INSTANCE_SYSTEMD_TEMPLATE:-/etc/systemd/system/nobrand-mieru@.service}"
MITA_INSTANCE_TMPFILES="${MITA_INSTANCE_TMPFILES:-/etc/tmpfiles.d/nobrand-mieru.conf}"
MITA_INSTANCE_OPENRC_PREFIX="${MITA_INSTANCE_OPENRC_PREFIX:-/etc/init.d/nobrand-mieru-}"
MITA_INSTANCE_RUNNER="${MITA_INSTANCE_RUNNER:-${NOBRAND_LIB_DIR}/mieru-instance-run}"
# 上游没有按用户清零指标的 API。isolated-v2 为每个用户挂载独立 metrics.pb，
# calendar 因而可以只重置目标用户；password/days 旧方案不会真正清零，已禁用。
QUOTA_RESET_METHOD="${QUOTA_RESET_METHOD:-metrics}"
INSTALL_SCRIPT_PATH="${NOBRAND_INSTALL_SCRIPT_PATH}"
NOBRAND_SNELL_STATE_DIR="${NOBRAND_SNELL_STATE_DIR:-${NOBRAND_STATE_DIR}/snell/instances}"
NOBRAND_SNELL_CONFIG_DIR="${NOBRAND_SNELL_CONFIG_DIR:-${NOBRAND_CONFIG_DIR}/snell/instances}"
NOBRAND_SNELL_RUNTIME_DIR="${NOBRAND_SNELL_RUNTIME_DIR:-${NOBRAND_BIN_DIR}/snell}"
NOBRAND_SNELL_SYSTEMD_TEMPLATE="${NOBRAND_SNELL_SYSTEMD_TEMPLATE:-/etc/systemd/system/nobrand-snell@.service}"
NOBRAND_SNELL_OPENRC_PREFIX="${NOBRAND_SNELL_OPENRC_PREFIX:-/etc/init.d/nobrand-snell-}"
NOBRAND_SNELL_RUNNER="${NOBRAND_SNELL_RUNNER:-${NOBRAND_LIB_DIR}/snell-run}"
SNELL_RELEASE_PAGE="https://kb.nssurge.com/surge-knowledge-base/release-notes/snell.md"

NOBRAND_HY2_STATE_DIR="${NOBRAND_HY2_STATE_DIR:-${NOBRAND_STATE_DIR}/hysteria2}"
NOBRAND_HY2_STATE_FILE="${NOBRAND_HY2_STATE_FILE:-${NOBRAND_HY2_STATE_DIR}/state.json}"
NOBRAND_HY2_CONFIG_DIR="${NOBRAND_HY2_CONFIG_DIR:-${NOBRAND_CONFIG_DIR}/hysteria2}"
NOBRAND_HY2_CONFIG_FILE="${NOBRAND_HY2_CONFIG_FILE:-${NOBRAND_HY2_CONFIG_DIR}/config.json}"
NOBRAND_HY2_CERT_FILE="${NOBRAND_HY2_CERT_FILE:-${NOBRAND_HY2_CONFIG_DIR}/hysteria2-cert.pem}"
NOBRAND_HY2_KEY_FILE="${NOBRAND_HY2_KEY_FILE:-${NOBRAND_HY2_CONFIG_DIR}/hysteria2-key.pem}"
NOBRAND_XRAY_BIN="${NOBRAND_XRAY_BIN:-${NOBRAND_BIN_DIR}/xray}"
NOBRAND_XRAY_ASSET_DIR="${NOBRAND_XRAY_ASSET_DIR:-${NOBRAND_LIB_DIR}/xray-assets}"
NOBRAND_HY2_SERVICE_NAME="nobrand-hysteria2"
NOBRAND_HY2_SYSTEMD_SERVICE="${NOBRAND_HY2_SYSTEMD_SERVICE:-/etc/systemd/system/nobrand-hysteria2.service}"
NOBRAND_HY2_OPENRC_SERVICE="${NOBRAND_HY2_OPENRC_SERVICE:-/etc/init.d/nobrand-hysteria2}"
TESTED_XRAY_VERSION="26.3.27"
TESTED_XRAY_AMD64_SHA256="23cd9af937744d97776ee35ecad4972cf4b2109d1e0fe6be9930467608f7c8ae"
TESTED_XRAY_ARM64_SHA256="4d30283ae614e3057f730f67cd088a42be6fdf91f8639d82cb69e48cde80413c"
NOBRAND_XRAY_RELEASE_API="https://api.github.com/repos/XTLS/Xray-core/releases/tags/v${TESTED_XRAY_VERSION}"
NOBRAND_HY2_TAG="nobrand-hysteria2-in"

NOBRAND_VLESS_STATE_DIR="${NOBRAND_VLESS_STATE_DIR:-${NOBRAND_STATE_DIR}/vless-sudoku}"
NOBRAND_VLESS_STATE_FILE="${NOBRAND_VLESS_STATE_FILE:-${NOBRAND_VLESS_STATE_DIR}/state.json}"
NOBRAND_VLESS_CLIENT_FILE="${NOBRAND_VLESS_CLIENT_FILE:-${NOBRAND_VLESS_STATE_DIR}/client.json}"
NOBRAND_VLESS_CONFIG_DIR="${NOBRAND_VLESS_CONFIG_DIR:-${NOBRAND_CONFIG_DIR}/vless-sudoku}"
NOBRAND_VLESS_CONFIG_FILE="${NOBRAND_VLESS_CONFIG_FILE:-${NOBRAND_VLESS_CONFIG_DIR}/config.json}"
NOBRAND_VLESS_SERVICE_NAME="nobrand-vless-sudoku"
NOBRAND_VLESS_SYSTEMD_SERVICE="${NOBRAND_VLESS_SYSTEMD_SERVICE:-/etc/systemd/system/nobrand-vless-sudoku.service}"
NOBRAND_VLESS_OPENRC_SERVICE="${NOBRAND_VLESS_OPENRC_SERVICE:-/etc/init.d/nobrand-vless-sudoku}"
NOBRAND_VLESS_TAG="nobrand-vless-sudoku-in"

# VLESS REALITY is an independent, named-instance product. It shares only the
# private official Xray runtime with HY2 and VLESS/Sudoku; state, configs,
# services, credentials, ports, firewall rows, and Ingress association are
# isolated per instance.
NOBRAND_REALITY_STATE_DIR="${NOBRAND_REALITY_STATE_DIR:-${NOBRAND_STATE_DIR}/vless-reality/instances}"
NOBRAND_REALITY_CONFIG_DIR="${NOBRAND_REALITY_CONFIG_DIR:-${NOBRAND_CONFIG_DIR}/vless-reality/instances}"
NOBRAND_REALITY_SYSTEMD_TEMPLATE="${NOBRAND_REALITY_SYSTEMD_TEMPLATE:-/etc/systemd/system/nobrand-vless-reality@.service}"
NOBRAND_REALITY_OPENRC_PREFIX="${NOBRAND_REALITY_OPENRC_PREFIX:-/etc/init.d/nobrand-vless-reality-}"
NOBRAND_REALITY_DEFENDER_PORT_MIN="${NOBRAND_REALITY_DEFENDER_PORT_MIN:-20000}"
NOBRAND_REALITY_DEFENDER_PORT_MAX="${NOBRAND_REALITY_DEFENDER_PORT_MAX:-29999}"
NOBRAND_REALITY_DEFENDER_DISPATCH_HOST="${NOBRAND_REALITY_DEFENDER_DISPATCH_HOST:-nobrand.invalid}"
NOBRAND_REALITY_DEFAULT_CAMOUFLAGE_MODE="auto"
NOBRAND_REALITY_DEFAULT_CAMOUFLAGE_PORT="443"
NOBRAND_REALITY_MIN_CLIENT_VER="0.0.0"
# This immutable release pool contains only Xray-OneClick discovery candidates
# that passed the exact NoBrand v3.2 REALITY/Vision + loopback-defender stack on
# Xray 26.3.27, Mihomo 1.19.30, and sing-box 1.13.20. Microsoft remains valid
# as an explicit user target, but its authenticated REALITY gate failed and it
# is intentionally absent from automatic selection.
REALITY_AUTO_QUALIFIED_CANDIDATES=(
  "www.abmindustriesgroup.com"
  "www.oracle.com"
  "www.ibm.com"
  "www.amazon.com"
  "www.samsung.com"
  "www.nvidia.com"
)

# TUIC v5 is the only supported TUIC generation. The tested runtime is an
# official, non-prerelease sing-box release; NoBrand never uses a system
# sing-box binary or config.
TUIC_PROTOCOL_VERSION=5
TUIC_V5_SUPPORTED=true
TUIC_V1_SUPPORTED=false
TUIC_V2_SUPPORTED=false
TUIC_V3_SUPPORTED=false
TUIC_V4_SUPPORTED=false
TESTED_SING_BOX_SERVER_VERSION="1.13.20"
TESTED_SING_BOX_AMD64_SHA256="646bc01bf128c32a12eb50d8690e387bba7504da7b1d65c704bd53916e38595a"
TESTED_SING_BOX_ARM64_SHA256="7f8187b1d1d30258cd4fa70892eaa232649f8f28b294078eeac719579e14cf42"
TESTED_SING_BOX_AMD64_MUSL_SHA256="ea5c79f74d88db43b58debbd510aac03e8c9432ed6de51b34f67271dddb5d05e"
TESTED_SING_BOX_ARM64_MUSL_SHA256="ab37923ee950695edf25733c10e7381b368ab9069617727be06ebd1b1b0e031a"
NOBRAND_SING_BOX_RELEASE_API="https://api.github.com/repos/SagerNet/sing-box/releases"
NOBRAND_SING_BOX_BIN="${NOBRAND_SING_BOX_BIN:-${NOBRAND_BIN_DIR}/sing-box}"
NOBRAND_SING_BOX_RUNTIME_META="${NOBRAND_SING_BOX_RUNTIME_META:-${NOBRAND_STATE_DIR}/tuic/runtime.json}"
NOBRAND_TUIC_STATE_DIR="${NOBRAND_TUIC_STATE_DIR:-${NOBRAND_STATE_DIR}/tuic/instances}"
NOBRAND_TUIC_CONFIG_DIR="${NOBRAND_TUIC_CONFIG_DIR:-${NOBRAND_CONFIG_DIR}/tuic/instances}"
NOBRAND_TUIC_SYSTEMD_TEMPLATE="${NOBRAND_TUIC_SYSTEMD_TEMPLATE:-/etc/systemd/system/nobrand-tuic@.service}"
NOBRAND_TUIC_OPENRC_PREFIX="${NOBRAND_TUIC_OPENRC_PREFIX:-/etc/init.d/nobrand-tuic-}"

# SSH Tunnel is a policy/account layer around the existing system sshd. It
# owns no listener, host key, package, firewall entry, or administrator key.
NOBRAND_SSH_GROUP="${NOBRAND_SSH_GROUP:-nobrand-ssh-tunnel}"
NOBRAND_SSH_STATE_DIR="${NOBRAND_SSH_STATE_DIR:-${NOBRAND_STATE_DIR}/ssh-tunnel}"
NOBRAND_SSH_STATE_FILE="${NOBRAND_SSH_STATE_FILE:-${NOBRAND_SSH_STATE_DIR}/state.json}"
NOBRAND_SSH_KEYS_DIR="${NOBRAND_SSH_KEYS_DIR:-${NOBRAND_SSH_STATE_DIR}/keys}"
NOBRAND_SSH_WATCHDOG_DIR="${NOBRAND_SSH_WATCHDOG_DIR:-${NOBRAND_SSH_STATE_DIR}/watchdog}"
NOBRAND_SSH_CONFIG_DIR="${NOBRAND_SSH_CONFIG_DIR:-${NOBRAND_CONFIG_DIR}/ssh-tunnel}"
NOBRAND_SSH_AUTHORIZED_KEYS_DIR="${NOBRAND_SSH_AUTHORIZED_KEYS_DIR:-${NOBRAND_SSH_CONFIG_DIR}/authorized_keys}"
NOBRAND_SSH_ACCOUNT_MARKER_DIR="${NOBRAND_SSH_ACCOUNT_MARKER_DIR:-${NOBRAND_SSH_CONFIG_DIR}/accounts}"
NOBRAND_SSH_GROUP_MARKER="${NOBRAND_SSH_GROUP_MARKER:-${NOBRAND_SSH_ACCOUNT_MARKER_DIR}/.group.json}"
NOBRAND_SSH_CONFIG_MAIN="${NOBRAND_SSH_CONFIG_MAIN:-/etc/ssh/sshd_config}"
NOBRAND_SSH_CONFIG_DROPIN="${NOBRAND_SSH_CONFIG_DROPIN:-/etc/ssh/sshd_config.d/90-nobrand-ssh-tunnel.conf}"
NOBRAND_SSH_BLOCK_BEGIN="# BEGIN NOBRAND SSH TUNNEL"
NOBRAND_SSH_BLOCK_END="# END NOBRAND SSH TUNNEL"

# Port Forward is a schema-v3 optional network feature. nftables state is
# confined to one NoBrand-owned table; Realm is installed to the private
# runtime directory and never replaces a system Realm installation.
NOBRAND_FORWARD_STATE_DIR="${NOBRAND_FORWARD_STATE_DIR:-${NOBRAND_STATE_DIR}/forward}"
NOBRAND_FORWARD_STATE_FILE="${NOBRAND_FORWARD_STATE_FILE:-${NOBRAND_FORWARD_STATE_DIR}/state.json}"
NOBRAND_FORWARD_CONFIG_DIR="${NOBRAND_FORWARD_CONFIG_DIR:-${NOBRAND_CONFIG_DIR}/forward}"
NOBRAND_FORWARD_REALM_CONFIG="${NOBRAND_FORWARD_REALM_CONFIG:-${NOBRAND_FORWARD_CONFIG_DIR}/realm.toml}"
NOBRAND_FORWARD_NFT_RULESET="${NOBRAND_FORWARD_NFT_RULESET:-${NOBRAND_FORWARD_CONFIG_DIR}/nftables.nft}"
NOBRAND_FORWARD_SYSCTL_STATE="${NOBRAND_FORWARD_SYSCTL_STATE:-${NOBRAND_FORWARD_STATE_DIR}/sysctl.json}"
NOBRAND_FORWARD_SYSCTL_FRAGMENT="${NOBRAND_FORWARD_SYSCTL_FRAGMENT:-/etc/sysctl.d/90-nobrand-forward.conf}"
NOBRAND_FORWARD_LOCK="${NOBRAND_FORWARD_LOCK:-${NOBRAND_LOCK_DIR}/forward.lock}"
NOBRAND_FORWARD_NFT_FAMILY="ip"
NOBRAND_FORWARD_NFT_TABLE="nobrand_forward_v4"
NOBRAND_REALM_BIN="${NOBRAND_REALM_BIN:-${NOBRAND_BIN_DIR}/realm}"
NOBRAND_REALM_RUNTIME_META="${NOBRAND_REALM_RUNTIME_META:-${NOBRAND_FORWARD_STATE_DIR}/realm-runtime.json}"
NOBRAND_REALM_SERVICE_NAME="nobrand-realm"
NOBRAND_REALM_SYSTEMD_SERVICE="${NOBRAND_REALM_SYSTEMD_SERVICE:-/etc/systemd/system/nobrand-realm.service}"
NOBRAND_REALM_OPENRC_SERVICE="${NOBRAND_REALM_OPENRC_SERVICE:-/etc/init.d/nobrand-realm}"
NOBRAND_REALM_RELEASE_API="https://api.github.com/repos/zhboner/realm/releases"
TESTED_REALM_VERSION="2.9.6"
TESTED_REALM_AMD64_MUSL_SHA256="b1cc335547bea8bb2a88178bef12ec7f2363e36200e7ea1d4e1e67627929bf65"
TESTED_REALM_ARM64_MUSL_SHA256="f4c0318dd86854da483dcb7645b4f39cae2cc3f91c688fef969d53220b949488"
PROTOCOL_FEATURE_FREEZE=true

# Xray-OneClick 57-hysteria2.sh 的原始候选集合，顺序也是非交互默认语义。
NOBRAND_HY2_SNI_CANDIDATES=(
  "www.abmindustriesgroup.com"
  "www.microsoft.com"
  "www.oracle.com"
  "www.ibm.com"
  "www.amazon.com"
  "www.samsung.com"
  "www.nvidia.com"
)
# 多用户端口池：相对主端口偏移，或 IP 尾号段内扫描
USER_PORT_POOL_START="${USER_PORT_POOL_START:-}"
USER_PORT_POOL_END="${USER_PORT_POOL_END:-}"

ACTION=""
MENU_MODE=0
MENU_SCRIPTS_READY=0
MAIN_MENU_ACTIVE=0
USER_MENU_HANDLED_RC=64
UNINSTALL_CANCELLED=0
UNINSTALL_PRESERVE_EXTERNAL=0
UNINSTALL_PRESERVE_PACKAGE=0
UNINSTALL_PRESERVE_USER=0
UNINSTALL_PRESERVE_GROUP=0
UNINSTALL_PRESERVE_SHARED=0
MITA_REINSTALL_TRIED=0
NOBRAND_INSTALL_STATE=""
NOBRAND_LIFECYCLE_OPERATION=""
NOBRAND_LIFECYCLE_SCOPE=""
NOBRAND_LIFECYCLE_ACTIVE=0
NOBRAND_LIFECYCLE_MUTATION_STARTED=0
NOBRAND_LIFECYCLE_LOCK_HELD=0
NOBRAND_MANAGER_SESSION_ACTIVE=0
NOBRAND_RECOVERY_EXPECTED_SCOPE=""
NOBRAND_RECOVERY_EXPECTED_STATE=""
NOBRAND_RECOVERY_EXPECTED_TX_PRESENT=0
NOBRAND_RECOVERY_EXPECTED_TX_STATUS=""
NOBRAND_RECOVERY_EXPECTED_TX_ID=""
NOBRAND_RECOVERY_EXPECTED_TX_RECORD=""
NOBRAND_MENU_EXIT_SUCCESS=4
YES=0
DRY_RUN=0
LANG_ZH=1
ENABLE_BBR=0
STAGE="初始化"

PORT=""
PORT_RANGE=""
PROTOCOL="TCP"
PROTOCOL_CLI=0
PROFILE="balanced"
PROFILE_CLI=0
ADVERTISE_HOST=""
ADVERTISE_PORT=""
ADVERTISE_CLI=0
USERNAME=""
PASSWORD=""
USERNAME_CLI=0
PASSWORD_CLI=0
OP_USER=""
MTU=1400
MTU_POLICY="safe"
MTU_REQUEST=""
MTU_CLI=0
MTU_AUTO_IFACE=""
MTU_AUTO_LINK=""
MTU_AUTO_FAMILY=""
MTU_AUTO_OVERHEAD=""
MULTIPLEXING="MULTIPLEXING_OFF"
HANDSHAKE_MODE="HANDSHAKE_NO_WAIT"
MULTIPLEXING_CLI=0
HANDSHAKE_CLI=0
TRAFFIC_PATTERN="conservative"
TRAFFIC_SEED=""
TRAFFIC_CLI=0
LOW_ENTROPY_MODE="LOW_ENTROPY_MODE_OFF"
LOW_ENTROPY_CLI=0
MIERU_CHANNEL="stable"
MIERU_CHANNEL_CLI=0
MIERU_VERSION=""
MIERU_VERSION_CLI=0
MIERU_RUNTIME_RESOLVED_VERSION=""
MIERU_RUNTIME_RESOLVED_ASSET=""
MIERU_RUNTIME_RESOLVED_URL=""
MIERU_RUNTIME_RESOLVED_CHECKSUM_URL=""
MIERU_RUNTIME_RESOLVED_SHA256=""
MIERU_RUNTIME_RESOLVED_CHANNEL=""
MIERU_RUNTIME_RESOLUTION_FALLBACK=0
PORT_CLI=0
PORT_RANGE_CLI=0
PORT_AUTO_SELECTED=0
INGRESS_PROFILE=""
INGRESS_PROFILE_CLI=0
INGRESS_PROFILE_ID=""
CLIENT_RPC_PORT=8964
CLIENT_SOCKS5_PORT=1080
CLIENT_HTTP_PORT=8080
USER_DEL_NAME=""
USER_SHOW_NAME=""
USER_QUOTA_MB=""
USER_QUOTA_DAYS=""
USER_QUOTA_MODE=""
USER_EXPIRE=""
USER_PACKAGE=""
USER_BANDWIDTH_MBPS=""
USER_RESTORE_FILE=""
USER_EXPORT_FILE=""
# 脚本只创建 clsact（缺失时）并维护自己记录的 filter；不删除或替换现有 qdisc。
TC_IFACE="${TC_IFACE:-}"
TC_OWNED_STATE="${TC_OWNED_STATE:-${MITA_MANAGER_STATE_DIR}/tc-owned.filters}"
TC_PREF_MIN=42000
TC_PREF_MAX=42999
# 0=首次安装的短暂兼容路径；1=使用 users.json 管理用户专属实例。
MULTI_USER_MODE=0

NOBRAND_ARGS_HANDLED=0
NOBRAND_PROTOCOL_FILTER=""
NOBRAND_BACKUP_ACTION=""
NOBRAND_BACKUP_PATH=""
SNELL_ACTION=""
SNELL_NAME=""
SNELL_VERSION="5"
SNELL_VERSION_CLI=0
SNELL_PSK=""
SNELL_QUIC_PROXY=""
SNELL_QUIC_CLI=0
SNELL_RESOLVED_VERSION=""
SNELL_RESOLVED_URL=""
SNELL_RESOLVED_STATUS=""
SNELL_RESOLVED_SHA256=""
HY2_ACTION=""
HY2_SNI=""
HY2_AUTH=""
HY2_OBFS=""
HY2_LISTEN="0.0.0.0"
VLESS_SUDOKU_ACTION=""
VLESS_SUDOKU_UUID=""
VLESS_SUDOKU_PASSWORD=""
VLESS_SUDOKU_LISTEN="0.0.0.0"
VLESS_SUDOKU_CLIENT_SOCKS_PORT="${VLESS_SUDOKU_CLIENT_SOCKS_PORT:-18080}"
VLESS_REALITY_ACTION=""
VLESS_REALITY_NAME=""
VLESS_REALITY_TARGET=""
VLESS_REALITY_TARGET_CLI=0
VLESS_REALITY_CAMOUFLAGE_MODE="$NOBRAND_REALITY_DEFAULT_CAMOUFLAGE_MODE"
VLESS_REALITY_TARGET_PORT="$NOBRAND_REALITY_DEFAULT_CAMOUFLAGE_PORT"
VLESS_REALITY_TARGET_PORT_CLI=0
VLESS_REALITY_FINGERPRINT="chrome"
VLESS_REALITY_SPIDER_X="/"
TUIC_ACTION=""
TUIC_NAME=""
TUIC_USER=""
TUIC_SNI=""
TUIC_CHANNEL="stable"
TUIC_VERSION=""
TUIC_USER_ACTION=""
TUIC_RUNTIME_RESOLVED_VERSION=""
TUIC_RUNTIME_RESOLVED_URL=""
TUIC_RUNTIME_RESOLVED_SHA256=""
TUIC_RUNTIME_RESOLVED_ASSET=""
SSH_TUNNEL_ACTION=""
SSH_TUNNEL_USER_ACTION=""
SSH_TUNNEL_USER=""
SSH_TUNNEL_WATCHDOG_TOKEN=""
ADVERTISE_AUTO_REQUESTED=0
FORWARD_ACTION=""
FORWARD_RULE_ID=""
FORWARD_NAME=""
FORWARD_NOTE=""
FORWARD_BACKEND=""
FORWARD_PROTOCOL=""
FORWARD_LISTEN_HOST=""
FORWARD_LISTEN_HOST_CLI=0
FORWARD_LISTEN_PORT=""
FORWARD_TARGET_HOST=""
FORWARD_TARGET_PORT=""
FORWARD_SOURCE_MODE="masquerade"
FORWARD_SOURCE_MODE_CLI=0
FORWARD_ADVANCED_CLI=0
FORWARD_IMPORT_FILE=""
FORWARD_EXPORT_FILE=""
FORWARD_THROUGH=""
FORWARD_INTERFACE=""
FORWARD_LISTEN_INTERFACE=""
FORWARD_TCP_TIMEOUT="5"
FORWARD_UDP_TIMEOUT="30"
FORWARD_PROXY_SEND="false"
FORWARD_PROXY_ACCEPT="false"
FORWARD_PROXY_VERSION="2"
FORWARD_PROXY_ACCEPT_TIMEOUT="5"
FORWARD_DNS_MODE="system"
FORWARD_DNS_PROTOCOL="tcp_and_udp"
FORWARD_DNS_NAMESERVERS=""
FORWARD_LISTEN_TRANSPORT=""
FORWARD_REMOTE_TRANSPORT=""
FORWARD_EXTRA_TARGETS=""
FORWARD_BALANCE="off"
FORWARD_WEIGHTS=""
INGRESS_ACTION=""
INGRESS_PROFILE_SELECTOR=""
INGRESS_NAME=""
INGRESS_TYPE=""
INGRESS_INTERFACE=""
INGRESS_ADDRESS=""
INGRESS_PORT_POLICY=""
INGRESS_RANGE_START=""
INGRESS_RANGE_END=""
INGRESS_RESERVED_PORTS=""
INGRESS_DISPLAY_HOST_DEFAULT=""
INGRESS_DISPLAY_PORT_POLICY=""
INGRESS_DISPLAY_PORT=""
INGRESS_ENABLED=""
INGRESS_ENFORCEMENT=""
INGRESS_APPLY_EXISTING=0
INGRESS_ENFORCEMENT_RESOLVED=""
INGRESS_ENFORCEMENT_METHOD=""
INGRESS_LOCAL_ADDRESS=""
INGRESS_LISTEN_HOST=""
INGRESS_NAME_CLI=0
INGRESS_TYPE_CLI=0
INGRESS_INTERFACE_CLI=0
INGRESS_ADDRESS_CLI=0
INGRESS_PORT_POLICY_CLI=0
INGRESS_RANGE_START_CLI=0
INGRESS_RANGE_END_CLI=0
INGRESS_RESERVED_CLI=0
INGRESS_DISPLAY_HOST_CLI=0
INGRESS_DISPLAY_PORT_POLICY_CLI=0
INGRESS_DISPLAY_PORT_CLI=0
INGRESS_ENABLED_CLI=0
INGRESS_ENFORCEMENT_CLI=0
